---
- hosts: docker_hub
  sudo: true
  remote_user: vagrant 
  vars:
    firewall:
      docker_hub:
        source_groups:
          - vagrant
        ports:
          - port: 5043
          - port: 6043
          - port: 7043
          - port: 8043
          - port: 443
          - port: 80
    nexus_hostname: nexus-test.openprovider.nl
  roles:
    - firewalld
  post_tasks:
    #
    # Install Docker Daemon
    #
    - name: Install yum repo for docker
      copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

    - name: yum update
      command: yum update -y

    - name: Install required RPMs
      yum: name={{item}} state=present
      with_items:
        - docker-engine
        - python-docker-py
    - service: name=docker state=restarted enabled=yes                                                
    #
    # Install Docker Registry
    #
    - name: Create data directory
      file: name=/var/lib/docker-hub/data state=directory

    - name: Create nginx configs directory
      file: name=/var/lib/docker-hub/auth state=directory

    - name: Add nginx config
      template: src=nginx.conf.j2 dest=/var/lib/docker-hub/auth/nginx.conf
    - name: Add nginx config (2)
      template: src=nginx-ssl.inc.j2 dest=/var/lib/docker-hub/auth/nginx-ssl.inc

    - name: Add ssl certificate to nginx config
      copy: src=ssl/ dest=/var/lib/docker-hub/auth/

    - name: Generate a password for the registry
      shell: docker run --rm --entrypoint htpasswd registry:2.4.0 -bn opimages FnrPmt4C > /var/lib/docker-hub/auth/nginx.htpasswd

    - name: Create docker registry container
      docker:
        name: registry
        image: registry:2.4.0
        restart_policy: always
        ports:
          - "5000:5000"
        volumes:
          - /var/lib/docker-hub/data:/var/lib/registry

    - name: Create sonatype/nexus3
      docker:
        name: nexus
        image: sonatype/nexus3
        restart_policy: always
        links:
          - registry:registry
        expose:
          - "8000"
          - "6000"
          - "7000"
        ports:
          - "8081:8081"
          - "8000:8000"
          - "6000:6000"
          - "7000:7000"

    - name: Create nginx container
      docker:
        name: nginx
        image: nginx:1.9
        restart_policy: always
        links:
          - nexus:nexus
          - registry:registry
        expose:
          - "5043"
          - "6043"
          - "7043"
          - "8043"
        ports:
          - "443:443"
          - "5043:5043"
          - "6043:6043"
          - "7043:7043"
          - "8043:8043"
          - "80:80"
        volumes:
          - /var/lib/docker-hub/auth:/etc/nginx/conf.d
          - /var/lib/docker-hub/auth/nginx.conf:/etc/nginx/nginx.conf:ro
