- copy: content={{ mesos_zk }} dest=/etc/mesos/zk
- copy: content=docker,mesos dest=/etc/mesos-slave/containerizers                                 
- copy: content=5mins dest=/etc/mesos-slave/executor_registration_timeout                         
- service: name=mesos-slave state=restarted enabled=yes                                           
- service: name=mesos-master state=stopped enabled=no       
