- copy: content={{ mesos_zk }} dest=/etc/mesos/zk
- copy: content={{zoo_quorum}} dest=/etc/mesos-master/quorum
- service: name=mesos-slave state=stopped enabled=no
- service: name=mesos-master state=restarted
