- stat: path=/etc/yum.repos.d/mesosphere.repo
  register: mesosphere_path
- command: rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
  when: not mesosphere_path.stat.exists
- yum: name={{item}} state=installed
  with_items:
    - cyrus-sasl-md5
    - subversion
    - mesos
