---
- name: yum update
  command: yum update -y
- name: Add docker.repo
  template: src=docker.repo.j2 dest=/etc/yum.repos.d/docker.repo
- yum: name={{item}} state=present
  with_items: 
    - docker-engine
    - python-docker-py
