---
- name: yum update
  command: yum update -y
- name: Add docker.repo
  template: src=docker.repo.j2 dest=/etc/yum.repos.d/docker.repo
- yum: name={{item}} state=present
  with_items: 
    - docker-engine
    - python-docker-py
- file: name=/etc/systemd/system/docker.service.d state=directory
- name: Add Docker daemon config
  template: src=docker.conf.j2 dest=/etc/systemd/system/docker.service.d/docker.conf
- command: systemctl daemon-reload                                              
- service: name=docker state=restarted enabled=yes                                                

