- hosts: consul-server
  sudo: true
  remote_user: vagrant 
  vars:
  tasks:
    - name: Install first Consul master
      docker:
        name: consul
        docker_url: "tcp://{{ansible_ssh_host}}:2375"
        image: gliderlabs/consul-server
        state: started
        net: host
        restart_policy: always
        hostname: "{{ ansible_fqdn }}"
        command: -server -advertise {{ ansible_ssh_host }} -bootstrap-expect=3
        ports:
          - "{{ ansible_ssh_host }}:8300:8300"
          - "{{ ansible_ssh_host }}:8301:8301"
          - "{{ ansible_ssh_host }}:8301:8301/udp"
          - "{{ ansible_ssh_host }}:8302:8302"
          - "{{ ansible_ssh_host }}:8302:8302/udp"
          - "{{ ansible_ssh_host }}:8400:8400"
          - "{{ ansible_ssh_host }}:8500:8500"
          - "{{ ansible_ssh_host }}:8600:8600"
      when: consul_join is undefined
    - name: Install Consul master
      docker:
        name: consul
        docker_url: "tcp://{{ansible_ssh_host}}:2375"
        image: gliderlabs/consul-server
        state: started
        net: host
        restart_policy: always
        hostname: "{{ ansible_fqdn }}"
        command: -server -advertise {{ ansible_ssh_host }} -join={{ consul_join }}
        ports:
          - "{{ ansible_ssh_host }}:8300:8300"
          - "{{ ansible_ssh_host }}:8301:8301"
          - "{{ ansible_ssh_host }}:8301:8301/udp"
          - "{{ ansible_ssh_host }}:8302:8302"
          - "{{ ansible_ssh_host }}:8302:8302/udp"
          - "{{ ansible_ssh_host }}:8400:8400"
          - "{{ ansible_ssh_host }}:8500:8500"
          - "{{ ansible_ssh_host }}:8600:8600"
      when: consul_join is defined
    - name: Get services list
      uri:
        url: http://{{ansible_ssh_host}}:8500/v1/agent/services
        body_format: json
        return_content: yes
      register: services_result
    - name: Add zookeeper service in consul
      uri:
        url: http://{{ansible_ssh_host}}:8500/v1/agent/service/register
        method: PUT
        body_format: json
        body: '{"name": "zookeeper", "tags": ["zookeeper"], "port": 2181}'
      when: services_result.json["zookeeper"] is undefined
      ignore_errors: yes
    - debug: var=services_result

- hosts: consul-client
  sudo: true
  remote_user: vagrant 
  vars:
  tasks:
    - name: Install consul client
      docker:
        name: consul
        docker_url: "tcp://{{ansible_ssh_host}}:2375"
        image: gliderlabs/consul-server
        state: started
        net: host
        restart_policy: always
        hostname: "{{ ansible_fqdn }}"
        command: -advertise {{ ansible_ssh_host }} -join={{ consul_join }}
        ports:
          - "{{ ansible_ssh_host }}:8300:8300"
          - "{{ ansible_ssh_host }}:8301:8301"
          - "{{ ansible_ssh_host }}:8301:8301/udp"
          - "{{ ansible_ssh_host }}:8302:8302"
          - "{{ ansible_ssh_host }}:8302:8302/udp"
          - "{{ ansible_ssh_host }}:8400:8400"
          - "{{ ansible_ssh_host }}:8500:8500"
          - "{{ ansible_ssh_host }}:8600:8600"

- hosts: consul
  sudo: true
  remote_user: vagrant 
  vars:
  tasks:
    - template: src=resolv.conf.j2 dest=/etc/resolv.conf
    - name: Install dnsmasq
      yum: name=dnsmasq state=installed
    - copy: content="server=/consul/{{ ansible_ssh_host }}#8600" dest=/etc/dnsmasq.d/10-consul
    - name: Enable dnsmasq
      service: name=dnsmasq enabled=on state=restarted
  tags: [dnsmasq]
