- hosts: docker
  sudo: true
  remote_user: vagrant 
  vars:
    docker_daemon_cluster_store: consul://192.168.2.2:8500
#    docker_daemon_default_gateway: "{{ ansible_ssh_host }}"
  roles:
    - docker/daemon
