- hosts: docker
  sudo: true
  remote_user: vagrant 
  vars:
    docker_daemon_cluster_store: consul://consul.service.consul:8500
    docker_daemon_dns: 172.17.0.1
    docker_daemon_dns_search: service.consul
  roles:
    - docker/daemon
