- include: mesos-install.yml
  tags: [mesos]

- include: docker-install.yml
  tags: [docker]


- include: consul-install.yml
  tags: [consul]

- include: swarm-install.yml
  tags: [swarm]

- hosts: spark-node
  sudo: true
  remote_user: vagrant 
  vars:
  roles:
    - role: spark/node
  tags: [spark]
