---
- hosts: consul-server
  sudo: true
  remote_user: vagrant 
  tasks:
    - ping:

- hosts: docker-swarm-master
  sudo: true
  remote_user: vagrant 
  vars:
    swarm_master_service_id: swarm-master
    docker_swarm_kv_store: "consul://consul.service.consul:8500"
  tasks:
    - name: Swarm master is running
      docker:
        name: swarm-master
        docker_url: "tcp://{{ansible_ssh_host}}:2375"
        image: swarm
        ports:
          - "{{ansible_ssh_host}}:4000:2375"
        command: manage --replication --advertise {{ansible_ssh_host}}:4000 {{docker_swarm_kv_store}}

- hosts: docker-swarm-node
  sudo: true
  remote_user: vagrant 
  vars:
    swarm_master_ips: "{{ hostvars|to_group_vars(groups,'docker-swarm-master')|map_on_attr('ansible_ssh_host') }}"
    docker_swarm_kv_store: "consul://consul.service.consul:8500"
  tasks:
    - name: Swarm node is running
      docker:
        name: swarm-node
        docker_url: "tcp://{{ansible_ssh_host}}:2375"
        image: swarm
        command: join --advertise {{ansible_ssh_host}}:2375 {{docker_swarm_kv_store}}
